//! BudgetLine DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::BudgetLine;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new BudgetLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBudgetLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "budget_id")]
    pub budget_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "account_id")]
    pub account_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cost_center_id")]
    pub cost_center_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "fiscal_period_id")]
    pub fiscal_period_id: Uuid,
    #[cfg_attr(feature = "validation", validate(range(min = 2020), range(max = 2100)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "fiscal_year")]
    pub fiscal_year: i32,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 12)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fiscal_month")]
    pub fiscal_month: Option<i32>,
    #[serde(alias = "planned_amount")]
    pub planned_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a BudgetLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBudgetLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "budget_id")]
    pub budget_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "account_id")]
    pub account_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cost_center_id")]
    pub cost_center_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "fiscal_period_id")]
    pub fiscal_period_id: Uuid,
    #[cfg_attr(feature = "validation", validate(range(min = 2020), range(max = 2100)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "fiscal_year")]
    pub fiscal_year: i32,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 12)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fiscal_month")]
    pub fiscal_month: Option<i32>,
    #[serde(alias = "planned_amount")]
    pub planned_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a BudgetLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBudgetLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "budget_id")]
    pub budget_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "cost_center_id")]
    pub cost_center_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "fiscal_period_id")]
    pub fiscal_period_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(min = 2020), range(max = 2100)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "fiscal_year")]
    pub fiscal_year: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 12)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "fiscal_month")]
    pub fiscal_month: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "planned_amount")]
    pub planned_amount: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchBudgetLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.budget_id.is_some() || self.company_id.is_some() || self.account_id.is_some() || self.cost_center_id.is_some() || self.fiscal_period_id.is_some() || self.fiscal_year.is_some() || self.fiscal_month.is_some() || self.planned_amount.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for BudgetLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BudgetLineResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub budget_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub account_id: Uuid,
    pub cost_center_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub fiscal_period_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub fiscal_year: i32,
    pub fiscal_month: Option<i32>,
    pub planned_amount: Decimal,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for BudgetLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BudgetLineListResponseDto {
    /// List of items
    pub items: Vec<BudgetLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BudgetLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BudgetLineResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BudgetLineSummaryDto {
    pub id: Uuid,
    pub budget_id: Uuid,
    pub company_id: Uuid,
    pub account_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<BudgetLine> for BudgetLineResponseDto {
    fn from(entity: BudgetLine) -> Self {
        Self {
            id: entity.id,
            budget_id: entity.budget_id,
            company_id: entity.company_id,
            account_id: entity.account_id,
            cost_center_id: entity.cost_center_id,
            fiscal_period_id: entity.fiscal_period_id,
            fiscal_year: entity.fiscal_year,
            fiscal_month: entity.fiscal_month,
            planned_amount: entity.planned_amount,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<BudgetLine> for BudgetLineSummaryDto {
    fn from(entity: BudgetLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            budget_id: entity.budget_id,
            company_id: entity.company_id,
            account_id: entity.account_id,
            created_at,
        }
    }
}

impl From<CreateBudgetLineDto> for BudgetLine {
    fn from(dto: CreateBudgetLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            budget_id: dto.budget_id,
            company_id: dto.company_id,
            account_id: dto.account_id,
            cost_center_id: dto.cost_center_id,
            fiscal_period_id: dto.fiscal_period_id,
            fiscal_year: dto.fiscal_year,
            fiscal_month: dto.fiscal_month,
            planned_amount: dto.planned_amount,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&BudgetLine> for BudgetLineResponseDto {
    fn from(entity: &BudgetLine) -> Self {
        Self {
            id: entity.id.clone(),
            budget_id: entity.budget_id.clone(),
            company_id: entity.company_id.clone(),
            account_id: entity.account_id.clone(),
            cost_center_id: entity.cost_center_id.clone(),
            fiscal_period_id: entity.fiscal_period_id.clone(),
            fiscal_year: entity.fiscal_year.clone(),
            fiscal_month: entity.fiscal_month.clone(),
            planned_amount: entity.planned_amount.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBudgetLineDto> for BudgetLine {
    fn from_create_dto(dto: CreateBudgetLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(BudgetLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBudgetLineDto> for BudgetLine {
    fn apply_update(mut self, dto: UpdateBudgetLineDto) -> backbone_core::ServiceResult<Self> {
        self.budget_id = dto.budget_id;
        self.company_id = dto.company_id;
        self.account_id = dto.account_id;
        self.cost_center_id = dto.cost_center_id;
        self.fiscal_period_id = dto.fiscal_period_id;
        self.fiscal_year = dto.fiscal_year;
        self.fiscal_month = dto.fiscal_month;
        self.planned_amount = dto.planned_amount;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to BudgetLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
