//! Budget DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Budget;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BudgetEnforcement;
use crate::domain::entity::BudgetStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Budget
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBudgetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(min = 2020), range(max = 2100)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "fiscal_year")]
    pub fiscal_year: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "date_from")]
    pub date_from: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "date_to")]
    pub date_to: NaiveDate,
    pub status: BudgetStatus,
    pub enforcement: BudgetEnforcement,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Budget
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBudgetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(min = 2020), range(max = 2100)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "fiscal_year")]
    pub fiscal_year: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "date_from")]
    pub date_from: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "date_to")]
    pub date_to: NaiveDate,
    pub status: BudgetStatus,
    pub enforcement: BudgetEnforcement,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Budget
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBudgetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(min = 2020), range(max = 2100)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "fiscal_year")]
    pub fiscal_year: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_from")]
    pub date_from: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_to")]
    pub date_to: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<BudgetStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enforcement: Option<BudgetEnforcement>,
}

impl PatchBudgetDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.description.is_some() || self.fiscal_year.is_some() || self.date_from.is_some() || self.date_to.is_some() || self.status.is_some() || self.enforcement.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Budget entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BudgetResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub fiscal_year: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date_from: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date_to: NaiveDate,
    pub status: BudgetStatus,
    pub enforcement: BudgetEnforcement,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Budget entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BudgetListResponseDto {
    /// List of items
    pub items: Vec<BudgetResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BudgetListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BudgetResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BudgetSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Budget> for BudgetResponseDto {
    fn from(entity: Budget) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            name: entity.name,
            description: entity.description,
            fiscal_year: entity.fiscal_year,
            date_from: entity.date_from,
            date_to: entity.date_to,
            status: entity.status,
            enforcement: entity.enforcement,
            metadata: entity.metadata,
        }
    }
}

impl From<Budget> for BudgetSummaryDto {
    fn from(entity: Budget) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreateBudgetDto> for Budget {
    fn from(dto: CreateBudgetDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            code: dto.code,
            name: dto.name,
            description: dto.description,
            fiscal_year: dto.fiscal_year,
            date_from: dto.date_from,
            date_to: dto.date_to,
            status: dto.status,
            enforcement: dto.enforcement,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Budget> for BudgetResponseDto {
    fn from(entity: &Budget) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            code: entity.code.clone(),
            name: entity.name.clone(),
            description: entity.description.clone(),
            fiscal_year: entity.fiscal_year.clone(),
            date_from: entity.date_from.clone(),
            date_to: entity.date_to.clone(),
            status: entity.status.clone(),
            enforcement: entity.enforcement.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBudgetDto> for Budget {
    fn from_create_dto(dto: CreateBudgetDto) -> backbone_core::ServiceResult<Self> {
        Ok(Budget::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBudgetDto> for Budget {
    fn apply_update(mut self, dto: UpdateBudgetDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.code = dto.code;
        self.name = dto.name;
        self.description = dto.description;
        self.fiscal_year = dto.fiscal_year;
        self.date_from = dto.date_from;
        self.date_to = dto.date_to;
        self.status = dto.status;
        self.enforcement = dto.enforcement;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Budget here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
