//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod budget_domain_policy;
pub mod budget_line_domain_policy;

pub use budget_domain_policy::BudgetDomainPolicy;
pub use budget_line_domain_policy::BudgetLineDomainPolicy;

// <<< CUSTOM
// END CUSTOM
