//! Application service for Budget entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `budget_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBudgetDto, UpdateBudgetDto};
use crate::domain::entity::Budget;
use crate::infrastructure::persistence::BudgetRepository;

/// Application service for Budget entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `budget_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BudgetServiceCustom {
///     inner: Arc<BudgetService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BudgetService = GenericCrudService<
    Budget,
    CreateBudgetDto,
    UpdateBudgetDto,
    BudgetRepository,
>;

// <<< CUSTOM
// END CUSTOM
