-- Budget Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the budget.budgets table.
-- Customize this file to add your initial data.

-- INSERT INTO budget.budgets (
--     id,
--     company_id,
--     code,
--     name,
--     description,
--     fiscal_year,
--     date_from,
--     date_to,
--     status,
--     enforcement,
--     metadata,
--     lines
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO budget.budgets (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

