-- BudgetLine Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the budget.budget_lines table.
-- Customize this file to add your initial data.

-- INSERT INTO budget.budget_lines (
--     id,
--     budget_id,
--     company_id,
--     account_id,
--     cost_center_id,
--     fiscal_period_id,
--     fiscal_year,
--     fiscal_month,
--     planned_amount,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO budget.budget_lines (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

