-- Enum types for budget module
-- Generated by metaphor-schema

-- Create budget_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'budget_status') THEN
        CREATE TYPE budget_status AS ENUM ('draft', 'confirmed', 'closed', 'cancelled');
    END IF;
END
$$;

-- Create budget_enforcement enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'budget_enforcement') THEN
        CREATE TYPE budget_enforcement AS ENUM ('warn', 'block');
    END IF;
END
$$;

