-- Migration: Create budgets table
-- Generated by metaphor-schema

-- Create budget_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'budget_status') THEN
        CREATE TYPE budget_status AS ENUM ('draft', 'confirmed', 'closed', 'cancelled');
    END IF;
END
$$;

-- Create budget_enforcement enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'budget_enforcement') THEN
        CREATE TYPE budget_enforcement AS ENUM ('warn', 'block');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS budget;

CREATE TABLE IF NOT EXISTS budget.budgets (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    fiscal_year INTEGER NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    status budget_status NOT NULL,
    enforcement budget_enforcement NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_budgets_company_id_code ON budget.budgets (company_id, code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_budgets_company_id_status ON budget.budgets (company_id, status);

CREATE INDEX IF NOT EXISTS idx_budgets_company_id_fiscal_year ON budget.budgets (company_id, fiscal_year);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_budgets_metadata_gin ON budget.budgets USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_budgets_metadata_deleted_at ON budget.budgets ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_budgets_metadata_created_at ON budget.budgets ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_budgets_metadata_updated_at ON budget.budgets ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION budget.budgets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS budgets_insert_audit ON budget.budgets;
CREATE TRIGGER budgets_insert_audit BEFORE INSERT ON budget.budgets
    FOR EACH ROW EXECUTE FUNCTION budget.budgets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS budgets_update_audit ON budget.budgets;
CREATE TRIGGER budgets_update_audit BEFORE UPDATE ON budget.budgets
    FOR EACH ROW EXECUTE FUNCTION budget.budgets_audit_timestamp();
