-- Company RLS fence for budget module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for budget.budgets
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE budget.budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget.budgets FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS budgets_company_isolation ON budget.budgets;
CREATE POLICY budgets_company_isolation ON budget.budgets
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for budget.budget_lines
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE budget.budget_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget.budget_lines FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS budget_lines_company_isolation ON budget.budget_lines;
CREATE POLICY budget_lines_company_isolation ON budget.budget_lines
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

