-- Migration: Create budget_lines table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS budget;

CREATE TABLE IF NOT EXISTS budget.budget_lines (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    budget_id UUID NOT NULL,
    company_id UUID NOT NULL,
    account_id UUID NOT NULL,
    cost_center_id UUID,
    fiscal_period_id UUID NOT NULL,
    fiscal_year INTEGER NOT NULL,
    fiscal_month INTEGER,
    planned_amount NUMERIC(18, 2) NOT NULL CHECK (planned_amount >= 0),
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_budget_lines_company_id_account_id_cost_center_id_fiscal_period_id ON budget.budget_lines (company_id, account_id, cost_center_id, fiscal_period_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_budget_lines_company_id_fiscal_period_id ON budget.budget_lines (company_id, fiscal_period_id);

CREATE INDEX IF NOT EXISTS idx_budget_lines_budget_id ON budget.budget_lines (budget_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_budget_lines_metadata_gin ON budget.budget_lines USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_budget_lines_metadata_deleted_at ON budget.budget_lines ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_budget_lines_metadata_created_at ON budget.budget_lines ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_budget_lines_metadata_updated_at ON budget.budget_lines ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION budget.budget_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS budget_lines_insert_audit ON budget.budget_lines;
CREATE TRIGGER budget_lines_insert_audit BEFORE INSERT ON budget.budget_lines
    FOR EACH ROW EXECUTE FUNCTION budget.budget_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS budget_lines_update_audit ON budget.budget_lines;
CREATE TRIGGER budget_lines_update_audit BEFORE UPDATE ON budget.budget_lines
    FOR EACH ROW EXECUTE FUNCTION budget.budget_lines_audit_timestamp();
