-- Audit Triggers Migration for budget module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Budget (budget.budgets)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION budget.budgets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS budgets_insert_audit ON budget.budgets;
CREATE TRIGGER budgets_insert_audit BEFORE INSERT ON budget.budgets
    FOR EACH ROW EXECUTE FUNCTION budget.budgets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS budgets_update_audit ON budget.budgets;
CREATE TRIGGER budgets_update_audit BEFORE UPDATE ON budget.budgets
    FOR EACH ROW EXECUTE FUNCTION budget.budgets_audit_timestamp();

-- ==============================================================================
-- Table: BudgetLine (budget.budget_lines)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION budget.budget_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS budget_lines_insert_audit ON budget.budget_lines;
CREATE TRIGGER budget_lines_insert_audit BEFORE INSERT ON budget.budget_lines
    FOR EACH ROW EXECUTE FUNCTION budget.budget_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS budget_lines_update_audit ON budget.budget_lines;
CREATE TRIGGER budget_lines_update_audit BEFORE UPDATE ON budget.budget_lines
    FOR EACH ROW EXECUTE FUNCTION budget.budget_lines_audit_timestamp();

