//! Event handler trait for BudgetLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BudgetLineEvent;

/// Event handler for BudgetLine events.
/// Implement this trait to react to BudgetLine lifecycle events.
pub trait BudgetLineEventHandler: EventHandler<BudgetLineEvent> {}
