//! Domain events for Budget entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Budget;

/// Domain events for Budget — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Budget>)` variant.
pub type BudgetEvent = CrudEvent<Budget>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Budget events.
pub type BudgetEventPublisher = Arc<dyn CrudEventPublisher<Budget> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBudgetEventPublisher = NoOpCrudEventPublisher<Budget>;
