//! Event handler trait for Budget events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BudgetEvent;

/// Event handler for Budget events.
/// Implement this trait to react to Budget lifecycle events.
pub trait BudgetEventHandler: EventHandler<BudgetEvent> {}
