//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod budget_events;
pub mod budget_event_handlers;
pub mod budget_line_events;
pub mod budget_line_event_handlers;

pub use budget_events::{BudgetEvent, BudgetEventPublisher, NoopBudgetEventPublisher};
pub use budget_event_handlers::BudgetEventHandler;
pub use budget_line_events::{BudgetLineEvent, BudgetLineEventPublisher, NoopBudgetLineEventPublisher};
pub use budget_line_event_handlers::BudgetLineEventHandler;

// <<< CUSTOM
// END CUSTOM
