//! BudgetLine seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial BudgetLine data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// BUDGETLINE SEEDER
// ============================================================================

/// Seeder for budget_line
pub struct SeedBudgetLineSeeder;

impl SeedBudgetLineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedBudgetLineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedBudgetLineSeeder {
    fn name(&self) -> &'static str {
        "SeedBudgetLineSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if budget.budget_lines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM budget.budget_lines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/budget_line_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM budget.budget_lines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
