//! Repository trait for BudgetLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BudgetLine aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::BudgetLine;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BudgetLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BudgetLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BudgetLinePaginatedResult {
    pub data: Vec<BudgetLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BudgetLineFilter {
    pub budget_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub account_id: Option<Uuid>,
    pub cost_center_id: Option<Uuid>,
    pub fiscal_period_id: Option<Uuid>,
    pub notes: Option<String>,
}

impl BudgetLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.budget_id.is_some() || self.company_id.is_some() || self.account_id.is_some() || self.cost_center_id.is_some() || self.fiscal_period_id.is_some() || self.notes.is_some()
    }
}

/// Repository trait for BudgetLine aggregate
///
/// This trait defines the persistence contract for BudgetLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BudgetLineRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new budget_line entity
    async fn save(&self, entity: &BudgetLine) -> Result<BudgetLine>;

    /// Find budget_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BudgetLine>>;

    /// Find all budget_line entities
    async fn find_all(&self) -> Result<Vec<BudgetLine>>;

    /// Update budget_line by ID
    async fn update(&self, id: &str, entity: &BudgetLine) -> Result<Option<BudgetLine>>;

    /// Delete budget_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List budget_line with pagination
    async fn list(&self, params: BudgetLinePaginationParams) -> Result<BudgetLinePaginatedResult>;

    /// List budget_line with pagination and filters
    async fn list_with_filters(&self, params: BudgetLinePaginationParams, filters: BudgetLineFilter) -> Result<BudgetLinePaginatedResult>;

    /// Count all budget_line entities
    async fn count(&self) -> Result<u64>;

    /// Count budget_line entities matching filters
    async fn count_with_filters(&self, filters: BudgetLineFilter) -> Result<u64>;

    /// Check if budget_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete budget_line by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted budget_line by ID
    async fn restore(&self, id: &str) -> Result<Option<BudgetLine>>;

    /// List soft-deleted budget_line entities
    async fn list_deleted(&self, params: BudgetLinePaginationParams) -> Result<BudgetLinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save budget_line entities
    async fn bulk_save(&self, entities: &[BudgetLine]) -> Result<Vec<BudgetLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
