//! Repository trait for Budget aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Budget aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Budget, BudgetEnforcement, BudgetStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BudgetPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BudgetPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BudgetPaginatedResult {
    pub data: Vec<Budget>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BudgetFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
    pub description: Option<String>,
    pub status: Option<BudgetStatus>,
    pub enforcement: Option<BudgetEnforcement>,
}

impl BudgetFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.description.is_some() || self.status.is_some() || self.enforcement.is_some()
    }
}

/// Repository trait for Budget aggregate
///
/// This trait defines the persistence contract for Budget entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BudgetRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new budget entity
    async fn save(&self, entity: &Budget) -> Result<Budget>;

    /// Find budget by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Budget>>;

    /// Find all budget entities
    async fn find_all(&self) -> Result<Vec<Budget>>;

    /// Update budget by ID
    async fn update(&self, id: &str, entity: &Budget) -> Result<Option<Budget>>;

    /// Delete budget by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List budget with pagination
    async fn list(&self, params: BudgetPaginationParams) -> Result<BudgetPaginatedResult>;

    /// List budget with pagination and filters
    async fn list_with_filters(&self, params: BudgetPaginationParams, filters: BudgetFilter) -> Result<BudgetPaginatedResult>;

    /// Count all budget entities
    async fn count(&self) -> Result<u64>;

    /// Count budget entities matching filters
    async fn count_with_filters(&self, filters: BudgetFilter) -> Result<u64>;

    /// Check if budget exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete budget by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted budget by ID
    async fn restore(&self, id: &str) -> Result<Option<Budget>>;

    /// List soft-deleted budget entities
    async fn list_deleted(&self, params: BudgetPaginationParams) -> Result<BudgetPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save budget entities
    async fn bulk_save(&self, entities: &[Budget]) -> Result<Vec<Budget>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
