//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod budget_repository;
pub mod budget_line_repository;

// Re-exports
pub use budget_repository::{
    BudgetRepository,
    BudgetPaginationParams,
    BudgetPaginatedResult,
    BudgetFilter,
};
pub use budget_line_repository::{
    BudgetLineRepository,
    BudgetLinePaginationParams,
    BudgetLinePaginatedResult,
    BudgetLineFilter,
};
