//! Repository for BudgetLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BudgetLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::BudgetLine;

/// Table name for BudgetLine entities
pub const TABLE_NAME: &str = "budget.budget_lines";

/// Repository for BudgetLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BudgetLineRepository(
    backbone_orm::GenericCrudRepository<BudgetLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BudgetLineRepository {
    type Target = backbone_orm::GenericCrudRepository<BudgetLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BudgetLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BudgetLineRepository, BudgetLine, soft_delete);
