//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod budget_repository;
mod budget_line_repository;

// Custom persistence modules
// <<< CUSTOM
pub mod budget_read_repository;
// END CUSTOM

// Re-exports
pub use budget_repository::BudgetRepository;
pub use budget_line_repository::BudgetLineRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use budget_read_repository::{
    AchievementRow, AchievedRow, BudgetReadRepository, ControlPosition, NormalBalanceRow,
    PeriodRow,
};
// END CUSTOM
