//! Validator for BudgetLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<BudgetLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::BudgetLine;

/// Validator type alias for BudgetLine entities.
pub type BudgetLineValidator = EntityValidator<BudgetLine>;

/// Build a validator for BudgetLine with all schema-defined field rules.
pub fn budget_line_validator() -> BudgetLineValidator {
    EntityValidator::new()
        .rule(NonNegative::new("fiscal_year", |e: &BudgetLine| e.fiscal_year as i64))
        .rule(OptionalNotBlank::new("notes", |e: &BudgetLine| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
