//! Validator for Budget entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Budget>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Budget;

/// Validator type alias for Budget entities.
pub type BudgetValidator = EntityValidator<Budget>;

/// Build a validator for Budget with all schema-defined field rules.
pub fn budget_validator() -> BudgetValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Budget| &e.code))
        .rule(RequiredString::new("name", |e: &Budget| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &Budget| e.description.as_deref()))
        .rule(NonNegative::new("fiscal_year", |e: &Budget| e.fiscal_year as i64))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
