//! Budget API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Budget CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BUDGET TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Budget
pub struct BudgetTestData;

impl TestDataGenerator for BudgetTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "fiscal_year": 1,
            "date_from": Utc::now().format("%Y-%m-%d").to_string(),
            "date_to": Utc::now().format("%Y-%m-%d").to_string(),
            "status": "draft",
            "enforcement": "warn",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "fiscal_year": 1,
            "date_from": Utc::now().format("%Y-%m-%d").to_string(),
            "date_to": Utc::now().format("%Y-%m-%d").to_string(),
            "status": "draft",
            "enforcement": "warn",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// BUDGET API TEST
// ============================================================================

/// Budget API test suite
pub struct BudgetApiTest {
    inner: GenericCrudTest<BudgetTestData>,
}

impl BudgetApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/budgets", "Budget");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BudgetTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BudgetApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_budget_crud() {
        let mut test = BudgetApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Budget specific tests here
// <<< CUSTOM TESTS END >>>
