//! BudgetLine API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the BudgetLine CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BUDGETLINE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for BudgetLine
pub struct BudgetLineTestData;

impl TestDataGenerator for BudgetLineTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "budget_id": Uuid::new_v4().to_string(),
            "account_id": Uuid::new_v4().to_string(),
            "cost_center_id": null,
            "fiscal_period_id": Uuid::new_v4().to_string(),
            "fiscal_year": 1,
            "fiscal_month": null,
            "planned_amount": 0,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "budget_id": Uuid::new_v4().to_string(),
            "account_id": Uuid::new_v4().to_string(),
            "cost_center_id": null,
            "fiscal_period_id": Uuid::new_v4().to_string(),
            "fiscal_year": 1,
            "fiscal_month": null,
            "planned_amount": 0,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/budgets", &super::budget_api_test::BudgetTestData).await {
            deps.push(("budget_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// BUDGETLINE API TEST
// ============================================================================

/// BudgetLine API test suite
pub struct BudgetLineApiTest {
    inner: GenericCrudTest<BudgetLineTestData>,
}

impl BudgetLineApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/budget_lines", "BudgetLine");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BudgetLineTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BudgetLineApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_budget_line_crud() {
        let mut test = BudgetLineApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add BudgetLine specific tests here
// <<< CUSTOM TESTS END >>>
