//! Budget Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::BudgetService;
use crate::application::service::BudgetLineService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Budget service
    pub budget_service: Arc<BudgetService>,
    /// BudgetLine service
    pub budget_line_service: Arc<BudgetLineService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        budget_service: Arc<BudgetService>,
        budget_line_service: Arc<BudgetLineService>
    ) -> Self {
        Self {
            budget_service,
            budget_line_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::BudgetModule) -> Self {
        Self {
            budget_service: module.budget_service.clone(),
            budget_line_service: module.budget_line_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    budget_service: Option<Arc<BudgetService>>,
    budget_line_service: Option<Arc<BudgetLineService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Budget service.
    pub fn with_budget_service(mut self, service: Arc<BudgetService>) -> Self {
        self.budget_service = Some(service);
        self
    }

    /// Set the BudgetLine service.
    pub fn with_budget_line_service(mut self, service: Arc<BudgetLineService>) -> Self {
        self.budget_line_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            budget_service: self.budget_service.expect("budget_service is required"),
            budget_line_service: self.budget_line_service.expect("budget_line_service is required"),
        }
    }
}
