//! Public events for Budget module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// BUDGET EVENTS
// ============================================================================

/// Event published when a Budget is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetCreatedEvent {
    pub id: BudgetId,
    pub data: BudgetDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Budget is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetUpdatedEvent {
    pub id: BudgetId,
    pub data: BudgetDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Budget is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetDeletedEvent {
    pub id: BudgetId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// BUDGETLINE EVENTS
// ============================================================================

/// Event published when a BudgetLine is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetLineCreatedEvent {
    pub id: BudgetLineId,
    pub data: BudgetLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a BudgetLine is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetLineUpdatedEvent {
    pub id: BudgetLineId,
    pub data: BudgetLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a BudgetLine is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetLineDeletedEvent {
    pub id: BudgetLineId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Budget module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BudgetEvent {
    BudgetCreated(BudgetCreatedEvent),
    BudgetUpdated(BudgetUpdatedEvent),
    BudgetDeleted(BudgetDeletedEvent),
    BudgetLineCreated(BudgetLineCreatedEvent),
    BudgetLineUpdated(BudgetLineUpdatedEvent),
    BudgetLineDeleted(BudgetLineDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for BudgetEventMetadata {
    fn default() -> Self {
        Self {
            module: "budget",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
