//! Budget Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Budget exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use budget::exports::{BudgetDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `BudgetDto` - Data transfer object for Budget
/// - `BudgetSummary` - Summary view of Budget
/// - `BudgetId` - Type-safe ID wrapper
/// - `BudgetLineDto` - Data transfer object for BudgetLine
/// - `BudgetLineSummary` - Summary view of BudgetLine
/// - `BudgetLineId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `BudgetCreatedEvent` - Published when Budget is created
/// - `BudgetUpdatedEvent` - Published when Budget is updated
/// - `BudgetDeletedEvent` - Published when Budget is deleted
/// - `BudgetLineCreatedEvent` - Published when BudgetLine is created
/// - `BudgetLineUpdatedEvent` - Published when BudgetLine is updated
/// - `BudgetLineDeletedEvent` - Published when BudgetLine is deleted
pub struct ExportSummary;
