//! Public types for Budget module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// BUDGET TYPES
// ============================================================================

/// Type-safe ID for Budget
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BudgetId(pub Uuid);

impl BudgetId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BudgetId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BudgetId> for Uuid {
    fn from(id: BudgetId) -> Self {
        id.0
    }
}

/// Data transfer object for Budget
///
/// This is the public representation of Budget for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetDto {
    pub id: BudgetId,
    pub code: String,
    pub name: String,
    pub description: Option<String>,
    pub fiscal_year: i32,
    pub date_from: NaiveDate,
    pub date_to: NaiveDate,
    pub status: BudgetStatus,
    pub enforcement: BudgetEnforcement,
    pub metadata: serde_json::Value,
}

/// Summary view of Budget for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetSummary {
    pub id: BudgetId,
    pub name: String,
    pub status: BudgetStatus,
}

/// Reference to Budget for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetRef {
    pub id: BudgetId,
}

// ============================================================================
// BUDGETLINE TYPES
// ============================================================================

/// Type-safe ID for BudgetLine
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BudgetLineId(pub Uuid);

impl BudgetLineId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BudgetLineId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BudgetLineId> for Uuid {
    fn from(id: BudgetLineId) -> Self {
        id.0
    }
}

/// Data transfer object for BudgetLine
///
/// This is the public representation of BudgetLine for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetLineDto {
    pub id: BudgetLineId,
    pub budget_id: Uuid,
    pub account_id: Uuid,
    pub cost_center_id: Option<Uuid>,
    pub fiscal_period_id: Uuid,
    pub fiscal_year: i32,
    pub fiscal_month: Option<i32>,
    pub planned_amount: Decimal,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of BudgetLine for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetLineSummary {
    pub id: BudgetLineId,
}

/// Reference to BudgetLine for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetLineRef {
    pub id: BudgetLineId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
