//! Budget Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::BudgetService;
pub use application::service::BudgetLineService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Budget module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let budget = BudgetModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = budget.all_crud_routes();
/// ```
pub struct BudgetModule {
    pub(crate) budget_service: Arc<BudgetService>,
    pub(crate) budget_line_service: Arc<BudgetLineService>,
    // <<< CUSTOM FIELDS
    pub(crate) budget_workflow_service: std::sync::Arc<
        application::service::budget_workflow_service::BudgetWorkflowService,
    >,
    pub(crate) budget_control_service: std::sync::Arc<
        application::service::budget_control_service::BudgetControlService,
    >,
    // END CUSTOM
}

impl BudgetModule {
    /// Create a new module builder
    pub fn builder() -> BudgetModuleBuilder {
        BudgetModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_budget_routes,
            create_budget_line_routes,
        };

        Router::new()
            .merge(create_budget_routes(self.budget_service.clone()))
            .merge(create_budget_line_routes(self.budget_line_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_budget_read_routes,
            create_budget_line_read_routes,
        };

        Router::new()
            .merge(create_budget_read_routes(self.budget_service.clone()))
            .merge(create_budget_line_read_routes(self.budget_line_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The validated write path (lifecycle verbs + the guard matrix) — the
    /// service behind [`presentation::http::create_guarded_budget_routes`].
    pub fn budget_workflow_service(
        &self,
    ) -> &std::sync::Arc<application::service::budget_workflow_service::BudgetWorkflowService> {
        &self.budget_workflow_service
    }

    /// The control/read side: posting evaluation (behind accounting's
    /// host-wired `BudgetControlPort`), achievements, coverage. The composing
    /// app's seam adapter calls this — there is no Cargo edge between the two
    /// modules, so the host maps the types.
    pub fn budget_control_service(
        &self,
    ) -> &std::sync::Arc<application::service::budget_control_service::BudgetControlService> {
        &self.budget_control_service
    }

    /// Guarded composition: validated verbs + control reads + safe GETs, NO
    /// generic budget/budget-line mutation. Mount behind the host's
    /// org-auth middleware (it inserts the request `OrgContext` and binds the
    /// ambient org scope the services relay).
    pub fn guarded_routes(&self) -> Router {
        presentation::http::create_guarded_budget_routes(self)
    }
    // END CUSTOM
}

/// Builder for BudgetModule
pub struct BudgetModuleBuilder {
    db_pool: Option<PgPool>,
}

impl BudgetModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<BudgetModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Budget service
        let budget_repository = Arc::new(BudgetRepository::new(db_pool.clone()));
        let budget_service = Arc::new(BudgetService::with_repository(budget_repository.clone()));

        // BudgetLine service
        let budget_line_repository = Arc::new(BudgetLineRepository::new(db_pool.clone()));
        let budget_line_service = Arc::new(BudgetLineService::with_repository(budget_line_repository.clone()));

        // <<< CUSTOM
        let budget_workflow_service = std::sync::Arc::new(
            application::service::budget_workflow_service::BudgetWorkflowService::new(
                db_pool.clone(),
            ),
        );
        let budget_control_service = std::sync::Arc::new(
            application::service::budget_control_service::BudgetControlService::new(
                db_pool.clone(),
            ),
        );
        // END CUSTOM

        Ok(BudgetModule {
            budget_service,
            budget_line_service,
            // <<< CUSTOM
            budget_workflow_service,
            budget_control_service,
            // END CUSTOM
        })
    }
}

impl Default for BudgetModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
