//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod budget_handler;
pub mod budget_line_handler;

// <<< CUSTOM
pub mod budget_ops_handler;
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use budget_handler::{create_budget_routes, create_budget_read_routes, create_budget_write_routes};
pub use budget_line_handler::{create_budget_line_routes, create_budget_line_read_routes, create_budget_line_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_budget_routes;
// END CUSTOM
